# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
